[global]
username = "ircfs-test"

[[server]]
username = "ircfs"
address = "irc.rizon.net"
alias = "rizon"
autoconnect = true
autojoin = ["#ircfs", "#cosarara"]

[[server]]
address = "chat.freenode.net"
port = 6697
ssl = true
autojoin = ["#ircfs"]
