[global]
nickname = "ircfs-test"

[[server]]
nickname = "ircfs"
server = "irc.rizon.net"
alias = "rizon"
autoconnect = true
autojoin = ["#ircfs", "#cosarara"]

[[server]]
server = "chat.freenode.net"
port = 6697
ssl = true
autojoin = ["#ircfs"]
