[global]
username = "riiir-test"

[[server]]
username = "riiir"
address = "irc.rizon.net"
alias = "rizon"
autoconnect = true
autojoin = ["#riiir", "#cosarara"]

[[server]]
address = "chat.freenode.net"
port = 6697
ssl = true
autojoin = ["#riiir"]
